name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use your required version

      - name: Replace environment variable in HTML
        run: |
          sed -i "s/DEFAULT_VALUE/$MY_ENV_VAR/" index.html
        env:
          MY_ENV_VAR: "This is a test value"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Change to your build output directory if needed